import AppKit

enum PanelSelectionDirection: Equatable {
    case left
    case right
    case up
    case down
    case lineStart
    case lineEnd
}

enum PanelTerminalInput: Equatable {
    case bytes([UInt8])
    case selection(direction: PanelSelectionDirection, byWord: Bool)
}

/// Converts a physical key and its modifiers into terminal-specific input
/// without touching AppKit window or application state.
enum PanelTerminalInputResolver {
    private static let userKeys: NSEvent.ModifierFlags = [.shift, .control, .option, .command]

    static func resolve(
        keyCode: UInt16,
        modifierFlags: NSEvent.ModifierFlags
    ) -> PanelTerminalInput? {
        let flags = modifierFlags.intersection(userKeys)

        if let bytes = controlBytes(keyCode: keyCode, flags: flags) {
            return .bytes(bytes)
        }
        if let bytes = optionDeleteBytes(keyCode: keyCode, flags: flags) {
            return .bytes(bytes)
        }
        if let bytes = homeEndBytes(keyCode: keyCode, flags: flags) {
            return .bytes(bytes)
        }
        if let bytes = pageKeyBytes(keyCode: keyCode, flags: flags) {
            return .bytes(bytes)
        }
        return keyboardSelectionInput(keyCode: keyCode, flags: flags)
    }

    /// Translate Control+letter into the canonical control byte regardless of
    /// the current keyboard layout. Shift is accepted because it does not change
    /// the control character generated by a physical letter key.
    private static func controlBytes(
        keyCode: UInt16,
        flags: NSEvent.ModifierFlags
    ) -> [UInt8]? {
        guard flags == [.control] || flags == [.control, .shift] else { return nil }
        guard let byte = KeyCodes.controlByte(forKeyCode: keyCode) else { return nil }
        return [byte]
    }

    /// Option+Delete → ESC DEL (readline backward-kill-word).
    private static func optionDeleteBytes(
        keyCode: UInt16,
        flags: NSEvent.ModifierFlags
    ) -> [UInt8]? {
        guard flags == [.option], keyCode == KeyCodes.delete else { return nil }
        return [0x1B, 0x7F]
    }

    /// Home / End → readline Ctrl+A / Ctrl+E. The raw control bytes work in
    /// readline, zle and fish without requiring shell-specific function-key bindings.
    private static func homeEndBytes(
        keyCode: UInt16,
        flags: NSEvent.ModifierFlags
    ) -> [UInt8]? {
        guard flags.isEmpty else { return nil }
        switch keyCode {
        case KeyCodes.home: return [0x01]
        case KeyCodes.end:  return [0x05]
        default:            return nil
        }
    }

    /// Plain PageUp / PageDown use the xterm sequences expected by full-screen
    /// applications. Modified variants fall through to SwiftTerm unchanged.
    private static func pageKeyBytes(
        keyCode: UInt16,
        flags: NSEvent.ModifierFlags
    ) -> [UInt8]? {
        guard flags.isEmpty else { return nil }
        switch keyCode {
        case KeyCodes.pageUp:   return [0x1B, 0x5B, 0x35, 0x7E]
        case KeyCodes.pageDown: return [0x1B, 0x5B, 0x36, 0x7E]
        default:                return nil
        }
    }

    /// Shift+arrow extends by character, Option+Shift by word, and
    /// Command+Shift+Left/Right to the corresponding line edge.
    private static func keyboardSelectionInput(
        keyCode: UInt16,
        flags: NSEvent.ModifierFlags
    ) -> PanelTerminalInput? {
        let shift: NSEvent.ModifierFlags = [.shift]
        let optionShift: NSEvent.ModifierFlags = [.option, .shift]
        let commandShift: NSEvent.ModifierFlags = [.command, .shift]
        guard flags == shift || flags == optionShift || flags == commandShift else { return nil }

        let direction: PanelSelectionDirection
        switch (keyCode, flags == commandShift) {
        case (KeyCodes.leftArrow, false):  direction = .left
        case (KeyCodes.rightArrow, false): direction = .right
        case (KeyCodes.upArrow, false):    direction = .up
        case (KeyCodes.downArrow, false):  direction = .down
        case (KeyCodes.leftArrow, true):   direction = .lineStart
        case (KeyCodes.rightArrow, true):  direction = .lineEnd
        default: return nil
        }
        return .selection(direction: direction, byWord: flags == optionShift)
    }
}
